nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: [ '*' ]
        allow_headers: [ '*' ]
        allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE' ]
        max_age: 3600
        hosts: [ ]
        origin_regex: false
    paths:
        '^/api/':
            allow_origin: [ '*' ]
            allow_headers: [ 'Content-Type', 'Authorization' ]
            allow_methods: [ 'POST' ]
            max_age: 3600